development:
  adapter: sqlite3
  database: db/development.sqlite3

test:
  adapter: sqlite3
  database: db/test.sqlite3

# ActiveRecord::Base.establish_connection(
#   adapter: "sqlite3",
#   database: "db/artists.sqlite"
# )